### ISSUE TITLE
Fix enter/leave animations

### ISSUE THREAD

**Issue by untemps** [untemps/svelte-use-tooltip#31]
When manipulated fastly, the animation breaks at some point. For eaxample,  the enter transition runs as usual then the tooltip hides.

**Comment by jrmoynihan** [comment]
I see this too.  I'm not sure where the issue is though.

Since you're assigning some CSS positioning calcs upon appending the tooltip, could the re-calculated positioning of the tooltip element be interfering with the pointer-events/hover-state of the element with the tooltip action on it?

Likewise, it might be more performant/consistent to use `transform: translate3d()` and `tranform-origin` rules to position the tooltip correctly.  I found that worked better for me than using the default behavior.

**Comment by untemps** [comment]
The issue comes from the way we attach the transitionend event. Since we don't check if a listener is already attached, the previous ones are triggered along with the current one, which lead to overlapping when we manipulate the tooltip trigger fastly.
PR is on its way.
